### ISSUE TITLE
Cannot read property 'IS_DEVELOPMENT' of undefined

### ISSUE THREAD

**Issue by wetterben** [Zimtir/SENT-template#60]
Hey, thanks for this massive template!

I just stumbled over this template and wanted to try it out right away. 
But when I start sapper, I get the following error message: 

````
/Users/ben/Development/SENT-template/__sapper__/build/server/server.js:28462
    const env = undefined[name];
                         ^

TypeError: Cannot read property 'IS_DEVELOPMENT' of undefined
    at getEnvKey (/Users/ben/Development/SENT-template/__sapper__/build/server/server.js:28462:26)
    at Object.<anonymous> (/Users/ben/Development/SENT-template/__sapper__/build/server/server.js:28467:25)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ben/Development/SENT-template/__sapper__/build/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
````

## My steps
`npm i`
`npm run dev`

## My environment 
Node: v12.14.1
NPM: 6.14.8
OS: MacOS 10.15.16

Thank you!

**Comment by Zimtir** [comment]
Hi, thank you for your notice

Now you need to create .env file based on template.env in the root of repository (like this https://github.com/Zimtir/SENT-template/blob/master/template.env)

I will add this to documentation later (because the work on documentation in progress)

This requirement to have .env file was created to developer not forgot and missed just index or point environment variables

**Comment by wetterben** [comment]
Hi @Zimtir 

Ah, I see. That makes sense. Now it works perfectly. Thank you very much for the quick answer. 

Even if you could figure it out yourself (I even wondered why the file is called `template.env`), it would be very handy to mention it in the documentation, for people such as me. 

Thanks again for the cool template!
